# Generated by Django 5.1 on 2024-08-11 23:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_load_root_user'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='customuser',
            managers=[
            ],
        ),
    ]
